---
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
exclude_paths:
- config/
- db/
- script/
- spec/
