inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 7.0
  Exclude:
    - 'spec/dummy/bin/*'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/node_modules/**/*'
    - 'spec/gemfiles/vendor/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/dummy/tmp/**/*'
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AssignmentInCondition:
  # the whole point is to notice this!
  AutoCorrect: false

Lint/EmptyBlock:
  AutoCorrect: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*_spec.rb
    - spec/dummy/config/environments/*.rb
    - spec/factories.rb

Metrics/ClassLength:
  Max: 125

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - spec/**/*.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/MethodParameterName:
  Enabled: false


Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/Date:
  EnforcedStyle: strict

Rails/FindBy:
  Enabled: true
  Include:
    - app/commands/**/*.rb
    - app/models/**/*.rb
    - app/view_models/**/*.rb

Rails/Output:
  AutoCorrect: false
  # we want these flagged not changed into Rails.logger

Rails/SkipsModelValidations:
  Enabled: false

# this regularly causes problems and benefits are not high enough
Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StderrPuts:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
