#!/usr/bin/env bash

if [ -n "$1" ]; then cat <<'HELP'; exit; fi
Usage: script/create-db-users
Create the thredded database users for all the supported databases.
If the `DB` environment variable is set, do the above only for that database.
HELP

set -e
log() { if [ -t 1 ]; then echo -e >&2 "\e[0;36m$@\e[0m"; else echo >&2 "$@"; fi }

create_mysql_user() {
  log 'Creating MySQL thredded user. MySQL root password required.'
  mysql --verbose -uroot -p <<'SQL'
-- This will create a user if one does not exist.
GRANT ALL PRIVILEGES ON `thredded_gem_dev`.* TO 'thredded'@'localhost' IDENTIFIED BY 'thredded';
GRANT ALL PRIVILEGES ON `thredded_gem_test`.* TO 'thredded'@'localhost';
SQL
}

create_postgresql_user() {
  log 'Creating Postgres thredded user. Sudo / root required.'
  sudo -u postgres psql --echo-all postgres <<'SQL'
DO
$body$
BEGIN
   IF NOT EXISTS (SELECT * FROM pg_catalog.pg_user WHERE usename = 'thredded') THEN
     CREATE ROLE thredded LOGIN PASSWORD 'thredded';
   END IF;
   ALTER USER thredded CREATEDB;
END
$body$
SQL
}

[ -z "$DB" -o "$DB" = 'mysql2' ] && create_mysql_user
[ -z "$DB" -o "$DB" = 'postgresql' ] && create_postgresql_user
