#!/usr/bin/env ruby
# frozen_string_literal: true

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/thredded/engine', __FILE__)

require 'rails/all'
require 'rails/engine/commands'
