class RenameMessageboardsFk < ActiveRecord::Migration
  def change
    if connection.adapter_name.downcase =~ /mysql/
      # Rename Rails-autogenerated foreign-key index
      rename_index :thredded_messageboard_users, :fk_rails_06e42c62f5, :fk_thredded_messageboard_users_user_detail_id
    end
  end
end
